import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "CNEC",
  description: "Generated by AKENTECH",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
